Jdp191102 12
metho/project-JDP-1911-02 pull request #8
Opened 2019-12-01 11:42 UTC by Mani3rrr

2019-12-02 14:59 UTC, coder-msl requested changes

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +  @GetMapping("/(productId}")
Zle wcięcie

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +
Pusta linia

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +import javax.persistence.*;
Ja nie lubię importować z gwiazdką bo moze powodować problemy przy rozbudowie

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +
Trochę pustuch linii

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +
Zbedna pusta linia

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        public Product mapToProduct(final ProductDto productDto) {
To chyba nie jest dokończone?

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +
Kilka zbędnych pustych linii

2019-12-02 14:59 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +
Pusta linia

2019-12-03 21:49 UTC, haker-msl commented
hej, czy ja mam się tutaj wypowiadać? Widzę 2 innych reviewerów dodanych. Czy coś zostało poprawione?

2019-12-04 17:20 UTC, pastorek89 requested changes
Zostawiłem tylko jedną uwagę do 31 linii w controllerze. Poza tym uważam, że ładnie i schludnie wszystko napisane :)

2019-12-04 17:20 UTC, pastorek89 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +
Widzę, że Mateusz już wszystko opisał :)

2019-12-04 17:20 UTC, pastorek89 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping("/(productId}")
Wydaje mi się, że tutaj jest literówka. zamiast "(" przed produktId powinno być "{"

2019-12-04 20:20 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping("/(productId}")
trafna uwaga!

2019-12-06 08:43 UTC, coder-msl approved these changes

2019-12-06 08:47 UTC, haker-msl commented
@pastorek89  ja klepnąłem, a Ty ? :)

2019-12-06 12:07 UTC, pastorek89 approved these changes

2019-12-06 12:09 UTC, pastorek89 commented
Już klepnąłem też @haker-msl :) @Mani3rrr Tylko konflikty jeszcze jak byś mógł rozwiązać przed wrzuceniem to będzie super :)

2019-12-09 19:35 UTC, merged